### ISSUE TITLE
Что нужно указать в self

### ISSUE THREAD

**Issue by ghost** [7vlad7/python-outline#3]
n1=DataTransfered.by_key(access_key=key.id)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataTransfered.by_key() missing 1 required positional argument: 'self'

**Comment by ghost** [comment]
@7vlad7

**Comment by 7vlad7** [comment]
@Der4ik0  Пример получения количества переданных байтов для ключа

```python
from outline.client import OutlineClient

client = OutlineClient('https://localhost:777/secret')

print(client.metrics.by_key(3))
# или
key = client.key(3)
print(key.metrics)

**Comment by ghost** [comment]
Большое спасибо, просто огромное

**Comment by turnme0n** [comment]
ебаааать ты даун, ебаааать ты тупой 
![IMG_20240206_201442_627](https://github.com/7vlad7/python-outline/assets/117026353/574ec822-3d2f-4645-9540-039b83c47d25)
